language: node_js
node_js:
    - "0.10"
before_script:
    - "npm install"
    - "npm install uupaa.compile.js"
    - "npm run minify"
script:
    - "NODE_ENV=production NODE_PATH=lib node --harmony test/index.node.js"

